= Account
[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/community-contracts/api/account

This directory includes contracts to build accounts for ERC-4337. These include:

 * {AccountCore}: An ERC-4337 smart account implementation that includes the core logic to process user operations.
 * {Account}: An extension of `AccountCore` that implements the recommended features for ERC-4337 smart accounts.
 * {AccountERC7579}: An extension of `AccountCore` that implements support for ERC-7579 modules.
 * {AccountERC7579Hooked}: An extension of `AccountERC7579` with support for a single hook module (type 4).
 * {ERC7821}: Minimal batch executor implementation contracts. Useful to enable easy batch execution for smart contracts.
 * {ERC7579SocialRecoveryExecutor}: A social recovery module for ERC-7579 accounts.

== Core

{{AccountCore}}

{{Account}}

== Extensions

{{AccountERC7579}}

{{AccountERC7579Hooked}}

{{ERC7821}}

{{ERC7579Modules}}

== ERC7579 Modules

This section includes several ERC-7579 Module implementations for {AccountERC7579}:

 * {ERC7579SocialRecoveryExecutor}: A social recovery module enabling account reconfiguration through a timelocked guardian-based consensus mechanism.

{{ERC7579SocialRecoveryExecutor}}