= Utilities

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/community-contracts/utils

Miscellaneous contracts and libraries containing utility functions you can use to improve security, work with new data types, or safely use low-level primitives.

 * {AbstractSigner}: Abstract contract for internal signature validation in smart contracts.
 * {ERC7739}: An abstract contract to validate signatures following the rehashing scheme from `ERC7739Utils`.
 * {ERC7739Utils}: Utilities library that implements a defensive rehashing mechanism to prevent replayability of smart contract signatures based on ERC-7739.
 * {ERC7913Utils}: utilities library that implements ERC-7913 signature verification with fallback to ERC-1271 and ECDSA.
 * {SignerECDSA}, {SignerP256}, {SignerRSA}: Implementations of an {AbstractSigner} with specific signature validation algorithms.
 * {ERC7913SignatureVerifierP256}, {ERC7913SignatureVerifierRSA}: Ready to use ERC-7913 signature verifiers for P256 and RSA keys
 * {Masks}: Library to handle `bytes32` masks.

== Cryptography

{{ERC7739}}

{{ERC7739Utils}}

=== Abstract signers

{{AbstractSigner}}

{{SignerECDSA}}

{{SignerP256}}

{{SignerRSA}}

=== ERC-7913

{{ERC7913Utils}}

{{ERC7913SignatureVerifierP256}}

{{ERC7913SignatureVerifierRSA}}

== Libraries

{{Masks}}
