:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]
:HybridProxy: pass:normal[xref:proxy.adoc#HybridProxy[`HybridProxy`]]
= Proxy

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/community-contracts/proxy

Variants of proxy patterns, which are contracts that allow to forward a call to an implementation contract by using `delegatecall`. This contracts include:

 * {HybridProxy}: An ERC-1967 proxy that uses the implementation slot as a beacon in a way that a user can upgrade to an implementation of their choice.

== General

:constructor: pass:normal[xref:#HybridProxy-constructor-address-bytes-[`++constructor++`]]
:_implementation: pass:normal[xref:#HybridProxy-_implementation--[`++_implementation++`]]

[.contract]
[[HybridProxy]]
=== `++HybridProxy++` link:https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v0.0.1/contracts/proxy/HybridProxy.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import "@openzeppelin/contracts/proxy/HybridProxy.sol";
```

A version of an ERC-1967 proxy that uses the address stored in the implementation slot as a beacon.

The design allows to set an initial beacon that the contract may quit by upgrading to its own implementation
afterwards. Transition between the "beacon mode" and the "direct mode" require implementation that expose an
upgrade mechanism that writes to the ERC-1967 implementation slot. Note that UUPSUpgradable includes security
checks that are not compatible with this proxy design.

WARNING: The fallback mechanism relies on the implementation not to define the {IBeacon-implementation} function.
Consider that if your implementation has this function, it'll be assumed as the beacon address, meaning that
the returned address will be used as this proxy's implementation.

[.contract-index]
.Functions
--
* `++constructor(implementation, data)++`
* `++_implementation()++`

[.contract-subindex-inherited]
.Proxy
* `++_delegate(implementation)++`
* `++_fallback()++`
* `++fallback()++`

--

[.contract-item]
[[HybridProxy-constructor-address-bytes-]]
==== `[.contract-item-name]#++constructor++#++(address implementation, bytes data)++` [.item-kind]#public#

Initializes the proxy with an initial implementation. If data is present, it will be used to initialize the
implementation using a delegate call.

[.contract-item]
[[HybridProxy-_implementation--]]
==== `[.contract-item-name]#++_implementation++#++() → address++` [.item-kind]#internal#

Returns the current implementation address according to ERC-1967's implementation slot.

IMPORTANT: The way this function identifies whether the implementation is a beacon, is by checking
if it implements the {IBeacon-implementation} function. Consider that an actual implementation could
define this function, mistakenly identifying it as a beacon.

