= Crosschain

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/community-contracts/api/crosschain

Gateways are contracts that enable cross-chain communication. These can either be a message source or a destination according to ERC-7786, which defines the following interfaces:

 * {IERC7786GatewaySource}: A contract interface to send a message to another contract on a different chain.
 * {IERC7786Receiver}: An interface that allows an smart contract to receive a crosschain message provided by a trusted destination gateway.

The library provides an implementation of an ERC-7786 receiver contract as a building block:

 * {ERC7786Receiver}: ERC-7786 cross-chain message receiver.

Given ERC-7786 could be enabled natively or via adapters. Developers can access interoperability protocols through gateway adapters. The library includes the following gateway adapters:

 * {AxelarGatewayBase}: Core gateway logic for the https://www.axelar.network/[Axelar] adapter.
 * {AxelarGatewaySource}: ERC-7786 source gateway adapter (sending side) for Axelar.
 * {AxelarGatewayDestination}: ERC-7786 destination gateway adapter (receiving side) for Axelar.
 * {AxelarGatewayDuplex}: ERC-7786 gateway adapter that operates in both directions (i.e. send and receive messages) using the Axelar network.

== Gateways

{{IERC7786GatewaySource}}

== Clients

{{IERC7786Receiver}}

{{ERC7786Receiver}}

== Adapters

=== Axelar

{{AxelarGatewayBase}}

{{AxelarGatewaySource}}

{{AxelarGatewayDestination}}

{{AxelarGatewayDuplex}}
