name: Transpile upgradeable

on:
  push:
    # branches:
    #   - master
    #   - release-v*
    branches-ignore:
      - '*-upgradeable'

jobs:
  transpile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Transpile to upgradeable
        run: bash scripts/upgradeable/transpile-onto.sh ${{ github.ref_name }}-upgradeable origin/${{ github.ref_name }}
        env:
          SUBMODULE_REMOTE: https://github.com/${{ github.repository }}.git
      - run: git push origin ${{ github.ref_name }}-upgradeable
